CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR,
    login VARCHAR,
    name VARCHAR,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS friends (
    offering_person_id BIGINT REFERENCES users,
    recipient_person_id BIGINT REFERENCES users,
    accepted BOOLEAN,
    PRIMARY KEY (offering_person_id, recipient_person_id)
);

CREATE TABLE IF NOT EXISTS mpa (
    id INTEGER PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    description VARCHAR,
    release_date DATE,
    duration INTEGER,
    mpa_id INTEGER REFERENCES mpa
);

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id BIGINT REFERENCES films,
    genre_id INTEGER REFERENCES genres,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users_ids_likes (
    film_id BIGINT REFERENCES films,
    user_id BIGINT REFERENCES users,
    PRIMARY KEY (film_id, user_id)
);